/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:391b1c2c-4216-4489-9b2e-295aad773136",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_K9GEky6pI",
    "aws_user_pools_web_client_id": "5p6p2grqh4gjrmor06bbro3udf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pcsgjgkocnbzpmk6zwevkbwzo4.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aswivp3najdlbgnrdpwr7s6o6y"
};


export default awsmobile;
